version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: palimpsest-web
    ports:
      - "8501:8501"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma
    volumes:
      - .:/app/

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data:
