# .streamlit/config.toml

[server]
# use the filesystem “poll” watcher so we don’t inspect torch._classes
fileWatcherType = "poll"  

# still reload on save
runOnSave = true  

# Optional: ignore any torch paths completely
watchIgnorePattern = "\\\\btorch\\\\b"
